# Generated by Django 2.0.7 on 2019-06-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='data',
        ),
        migrations.AddField(
            model_name='node',
            name='data_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='data_logic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='input_type',
            field=models.CharField(default='null', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='question',
            field=models.CharField(default='null', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=240),
        ),
    ]
