# Generated by Django 3.0.2 on 2020-02-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontree',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='node',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddConstraint(
            model_name='decisiontree',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique tree slug per user'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('slug', 'decision_tree'), name='unique nodeslug per tree'),
        ),
    ]
