# Generated by Django 2.0.7 on 2019-03-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiontree',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
