# Generated by Django 3.0.3 on 2020-03-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='question',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='node',
            name='data_answer',
        ),
        migrations.RemoveField(
            model_name='node',
            name='data_logic',
        ),
        migrations.RemoveField(
            model_name='node',
            name='input_type',
        ),
        migrations.AddField(
            model_name='node',
            name='inputs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
