# Generated by Django 2.0.7 on 2019-06-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190607_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='new_node',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
