# Generated by Django 3.0.3 on 2020-03-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200304_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
