# Generated by Django 2.0.7 on 2019-03-29 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_decisiontree_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontree',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
