# Generated by Django 2.0.7 on 2019-04-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190401_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='slugify',
            field=models.SlugField(default='', unique=True),
        ),
    ]
