# Generated by Django 2.0.7 on 2019-11-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_node_start_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='end_node',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
