# Generated by Django 2.0.7 on 2019-11-11 17:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_node_end_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
