# Generated by Django 2.0.7 on 2019-06-02 11:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190402_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='data',
        ),
        migrations.AddField(
            model_name='node',
            name='data_answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='data_logic',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='input_type',
            field=models.CharField(default='null', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='question',
            field=models.CharField(default='null', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=240),
        ),
    ]
