# Generated by Django 2.0.7 on 2019-06-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190602_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='data_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='data_logic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
