# Generated by Django 2.0.7 on 2019-02-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisiontree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
    ]
