# Generated by Django 2.0.7 on 2019-03-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisiontree', '0003_auto_20190328_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisiontree',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='node',
            name='decision_tree',
        ),
        migrations.DeleteModel(
            name='DecisionTree',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
